Продвинутые линтеры
Вывод golangci-lint:
duplicates_log\main.go:50:6: `FS` is unused (deadcode)
type FS interface {
     ^
duplicates_log\main.go:43:10: Error return value of `os.Chdir` is not checked (errcheck)
        os.Chdir(input)
                ^

Реализация:
1. Интерфейс FS сделан для тестирования.
2. Добавила проверку на ошибку с логированием.